# Please build this Dockerfile and use the following command:
# docker run --rm -it \
#    -e LOCAL_USER_NAME="`id -u -n`" -e LOCAL_USER_ID="`id -u`" -e LOCAL_GROUP_NAME="`id -g -n`" -e LOCAL_GROUP_ID="`id -g`" \
#    -e LOCAL_GITCONFIG_USERNAME="`git config user.name`" -e LOCAL_GITCONFIG_EMAIL="`git config user.email`" \
# [Image ID] /bin/bash -c "[Your commands]"

ARG VERSION=22.04
FROM ubuntu:${VERSION}

RUN apt-get update --fix-missing
RUN apt-get -y install gosu
COPY files/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

#################################
# Linux projects common setting #
#################################
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing

# Install Yocto build host packages (https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html)
RUN apt-get -y install gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool file locales libacl1

# For LV/LY projects build need:
RUN apt-get -y install gcc-multilib uuid-dev locales-all libsqlite3-0 pkg-config libstdc++-12-dev

RUN ln -s /usr/bin/python3 /usr/bin/python

# For LV/LY projects build environment:
ENV SHELL=/bin/bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh


