# bbmask
BBMASK .= "|meta-clang/recipes-devtools/m4/"
BBMASK .= "|meta-qti-bsp/meta-qti-base/recipes-extended/bzip2/bzip2_1.0.6.bbappend"
BBMASK .= "|meta-qti-bsp/meta-qti-base/recipes-gnome/gdk-pixbuf/gdk-pixbuf_%.bbappend"
BBMASK .= "|meta-qti-bsp/meta-qti-agl"
BBMASK .= "|meta-virtualization/recipes-core/runx/runx_git.bb"
BBMASK .= "|meta-virtualization/recipes-devtools/go/go-build_git.bb"
BBMASK .= "|meta-virtualization/recipes-extended/images/xen-guest-image-minimal.bb"